### ISSUE TITLE
Should psi be 1D too when N2 is 1D?

### ISSUE THREAD

**Issue by roxyboy** [bderembl/qgutils#1]
The stream function (psi) seems to be reshaped from 1D to 3D when N2 is also 1D. I think psi should be allowed to be 3D even when N2 is 1D.
https://github.com/bderembl/qgutils/blob/b13b4c02819137be18aa558e275d958064cbe4cf/qgutils/grid.py#L37

**Comment by bderembl** [comment]
Yes, I think you can use 3d psi with 1d N2.

However, as the description of this routine says: it is likely that I messed up something there (accumulation of bad choices). Do you have a specific example that does not work?

**Comment by roxyboy** [comment]
I'm getting the following error where I think `reshape3d` is trying to reshape a 1D psi to 3D?
![Screen Shot 2021-02-28 at 6 14 00 PM](https://user-images.githubusercontent.com/8934026/109427034-cfc77780-79f0-11eb-927c-654851d0ec90.png)

**Comment by bderembl** [comment]
yes, this should not happen. need to rewrite this routine...

**Comment by bderembl** [comment]
in the meantime you can reshape N2 to (nz,1,1)

**Comment by roxyboy** [comment]
I think things need to be imported from `operators.py` in `omega.py`:
https://github.com/bderembl/qgutils/blob/b13b4c02819137be18aa558e275d958064cbe4cf/qgutils/omega.py#L41

**Comment by bderembl** [comment]
this commit 193bba0d7ab74a0942a78abbaaedb36d8b6950f6 should temporarily fix the reshape issue

**Comment by bderembl** [comment]
fixed the import as well

**Comment by roxyboy** [comment]
I think things need to be imported from `mgd2d.py` as well...?

**Comment by roxyboy** [comment]
> I think things need to be imported from `mgd2d.py` as well...?

I made a PR #2 .

**Comment by bderembl** [comment]
should work now
